### ISSUE TITLE
Linchpin pip installation requires python.h

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1113]
When installing Linchpin in a clean environment, such as a container, using `pip install linchpin` its dependencies will require python.h (python-devel) and gcc. Looking into requirements.txt it seems that are number of packages shouldn't be there:
pyasn1
boto
setuptools
boto3
shade
ipaddress
openshift
apache-libcloud
pycrypto
pyopenssl
configparser

Some of the packages maybe used by Ansible modules, but then they should be in `extra_requires`. Other required only for setup, for that we have `setup_requires` and  lsay some maybe are no longer needed. In any case Linchpin dependency should be slim as possible.

**Comment by samvarankashyap** [comment]
We would like to support the core providers(aws, openstack, gce, openshift) of linchpin by default outofbox.
Due to the following requirements are must
```
boto
boto3
shade
openshift
apachelibcloud 
```
The reason the other requirements are listed are to make sure the linchpin does not break with python3 with their minimal versions. 
python-devel and gcc are linchpin . However, we can narrow down the packages that would be specific to linchpin requirement from python-devel.

**Comment by abraverm** [comment]
:+1:

**Comment by samvarankashyap** [comment]
@abraverm  with recent changes in PR #1091 python-devel, gcc are no longer necessary for installing linchpin. I tried it personally on centos distro. it works. 
closing the issue.
