### ISSUE TITLE
More levels of logging

### ISSUE THREAD

**Issue by optak** [CentOS-PaaS-SIG/linchpin#1234]
Current output is too verbose for majority of use cases, but maybe not enough for others.
Please consider printing just most important info to stdout/stderr and create debug log for investigation. This way, uses are not overwhelmed by output, but when something happen, they can find relevant info in log.

**Comment by 14rcole** [comment]
Closing because we don't think we'll have the bandwidth to handle this RFE before LinchPin goes into mantainence mode.  @optak if you'd like to pick it up yourself you're more than welcome to do so

A couple of workaround options include redirecting stdout (which should include all of the Ansible output) to a log or using the progress monitor with verbosity=0.  This will provide info on the status of provisioning without creating a wall of text
