### ISSUE TITLE
Libvirt "minimal" provisioning does not work

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#1279]
When provisioning with libvirt, only a handful of fields are required.  Some fields, such as `uri` and `networks` will throw errors if they do not exist even though they are not required.  I wouldn't be surprised if these errors cropped up in other providers as well.  In addition to fixing these bugs, we need to set up a "minimal" integration test for each provider that tests a deployment with only the required fields

**Comment by Dannyb48** [comment]
I file something similar for Libvirt as well because I noticed the same thing in my testing #1244 . I believe you are correct in stating this has probably cropped into other providers. I've seen this as well with os_server, for example  where even though count is said to be optional, the playbooks actually depend on that field being there.

**Comment by 14rcole** [comment]
It definitely exists in AWS as well.  It seems like we just don't have defaults set up for everything.  I'm working through the providers beginning with libvirt to get it resolved

**Comment by 14rcole** [comment]
Fixed by #1287
