### ISSUE TITLE
Openshift provision returns empty inventory

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1281]
There seems to be no inventory fitler implementation for Openshift, thus resources (pods\containers)  created with Linchpin are not listed in the inventory. This issue reproducable with Linchpin example for Openshift deployment.

**Comment by samvarankashyap** [comment]
@abraverm 
When openshift provider was included in linchpin we did not anticipate the requirement for inventory and was just used as a means to provision openshift resources. 
If an inventory is generated what details are you expecting in the inventory. 
is it the container IP Address or service endpoint or any other thing provisionined ? 
Due to a multitude of options, we choose to remain as just provisioner for openshift instead at that point of time

**Comment by abraverm** [comment]
In case of Pod deployment I would expect to find pod name and endpoint. The reason is that pod encapsulates everything needed from it even if it runs in multiple containers, and while Ansible will not do anything in the pod, it will use the endpoint for some other part in the deployment. I think endpoints is the right option because the nature of Pods and containers is that they can be rebuild, scale and etc and it should be transperent to the user.
