### ISSUE TITLE
Some integration tests are disabled

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#1421]
We should go through each of these and decide whether to delete them, re-enable them, or comment explaining why they're disabled and when they may be re-enabled

* aws/05_aws_ec2_vpc_endpoint
* aws/06_aws_ec2_elb_lb
* aws/07_aws_ec2_template
* aws/08_aws_ec2_vpc_nat_gateway
* combined/01_beaker_openstack
* general/01_minimal
* inventory/01_template_inventory
* libvirt/02_libvirt-storage
* libvirt/03_libvirt-network
* libvirt/04_libvirt-network-dns
* libvirt/05_libvirt-builtins
* libvirt/06_libvirt-multi-node-network
* libvirt/07_libvirt-static-ip
* openshift/01_openshift-create-template
* openstack/02_os-server-template
* openstack/11_os-port
* openstack/12_os-zone
* openstack/13_os-recordset

**Comment by samvarankashyap** [comment]
The following are the reasons why the above tests are disabled
aws/05_aws_ec2_vpc_endpoint --> VPC endpoint test is disabled due to quota restrictions. we need a clean up job to enable it in case of incomplete failures
aws/06_aws_ec2_elb_lb -->  aws_ec2_elb_lb disabled due to quota restrictions. we need a clean up job to enable it in case of incomplete failures
aws/07_aws_ec2_template --> Duplicate tests for ec2 provisioning template functionality is already tests. 
aws/08_aws_ec2_vpc_nat_gateway -> aws_ec2_elb_lb disabled due to quota restrictions. we need a clean up job to enable it in case of incomplete failures
combined/01_beaker_openstack --> Takes a high toll on infra and increases testing times. 
general/01_minimal -->  Takes a high toll on infra and increases testing times. duplication of multiple tests
inventory/01_template_inventory -->  duplicate test. currently not enabled. 
libvirt/02_libvirt-storage --> Need to be enabled, disabled due to  no infra support
libvirt/03_libvirt-network --> Need to be enabled, disabled due to  no infra support
libvirt/04_libvirt-network-dns  --> Need to be enabled, disabled due to  no infra support
libvirt/05_libvirt-builtins --> Need to be enabled, disabled due to  no infra support
libvirt/06_libvirt-multi-node-network --> Need to be enabled, disabled due to  no infra support
libvirt/07_libvirt-static-ip --> Need to be enabled, disabled due to  no infra support
openshift/01_openshift-create-template --> Openshift templates goes into error state on destroy due to openshift api. Which is a bug on openstack side
openstack/02_os-server-template --> It is a duplicate test for os_server provisioning since it is also tested as a part of unit tests. 
openstack/11_os-port --> No infrastructure support for testing os-port module
openstack/12_os-zone --> No infrastructure support for testing os-zone module 
openstack/13_os-recordset --> No infrastructure support for testing os-recordset module 


All the above tests can be re-enabled once we collect mock data for all the providers. 
we can also add tests for community maintained providers like VMware, docker, Duffy, too.
