### ISSUE TITLE
PoC on provisioning/deprovisioning VMs, BMs in IBM Cloud

### ISSUE THREAD

**Issue by maneeshmehra** [CentOS-PaaS-SIG/linchpin#1450]
The purpose of this PoC is to validate that LinchPin is able to provision/deprovision physical and virtual system resources within the IBM Cloud.

As part of this request, LinchPin should be able to:
0. Connect to the IBM Cloud (using existing/new Ansible modules)
1. Provision a VM of smallest size
2. Deprovision the VM created in #1 above
3. Provision a Bare Metal server of smallest size
4. Deprovision the VM created in #3 above.

The intent for this PoC is to leverage as much of the existing capabilities available within Ansible for interacting with the IBM Cloud. In the event of lack of such capability, any new capability should be added to Ansible with the intent that it could be invoked outside of LinchPin too. Changes on the LinchPin side should be limited to just the amount needed to identify the request targeted towards the IBM Cloud and for handling any IBM-Cloud specific data.

**Comment by samvarankashyap** [comment]
IBM cloud POC investigation summary:

- IBM cloud uses SoftLayer API in order to provisioning most of its resources
- Softlayer Python API client is currently available [1]
- Ansible has a community-contributed sl_vm module used for provisioning multiple types of virtual servers aka VMS. However, the sl_vm ansible module is currently not maintained anymore and the community is looking for contributors.  
- sl_vm module needs many updates to support linchpin’s multi credential management
- Other IBM cloud services such as bare metal provisioning do not have any ansible modules supporting them. 
- SoftLayer API has extensive support for most of the services provided by the IBM cloud. 
- we can always write ansible modules wrappers around SoftLayer API
- During the POC we are able to achieve full integration with linchpin to provision, teardown IBM virtual servers which involved making changes to the existing sl_vm module. 
- Since IBM bare-metal provision does not have an ansible module. We had to create a new module to make it possible. However, due to very long provisioning wait times and no transaction id support after the machine is provisioned. It is much more complicated to integrate bare metal provisioning in linchpin
- Though IBM bare metal provisioning claims to provision within 1 to 4 hours of provisioning when running with Softlayer API it on an average 8 hours and more to provision a single machine. This is due to the long automatic approval process involved in the backend.

[1] https://softlayer-python.readthedocs.io/en/latest/
[2] https://docs.ansible.com/ansible/latest/modules/sl_vm_module.html

**Comment by samvarankashyap** [comment]
IBM POC Is available on my personal branch
https://github.com/samvarankashyap/linchpin/tree/ibm_cloud_poc
Closing the issue for now. 
We will be re-opening it if it needs to be integrated back to linchpin.
