### ISSUE TITLE
Beaker-client not available after linchpin is installed

### ISSUE THREAD

**Issue by rywillia** [CentOS-PaaS-SIG/linchpin#307]
I am trying to use linchpin to provision resources in beaker. I have installed linchpin by pip [1] and beaker-client package is not installed. In order for me to provision I need to manually install beaker-client.

Is this a known step that needs to be performed after linchpin is installed to use beaker? Do you plan to install beaker-client with linchpin?

[1] https://pypi.python.org/pypi/linchpin/1.0.1

**Comment by herlo** [comment]
Yes, this is a known step. Since beaker isn't among the core providers, this detail has yet to be documented (wow, we have a lot of documenting to do). Essentially, if you do a ```pip install linchpin[beaker]```, it will install the beaker-client libraries. If you need the kerberos libs (beaker now supports oAuth2, btw), you'd also want to run ```pip install linchpin[krbV]```. 

Hope this helps, and I hope to get this documented soon!
