### ISSUE TITLE
Beaker timeout should be configurable via the topology

### ISSUE THREAD

**Issue by jaypoulz** [CentOS-PaaS-SIG/linchpin#424]
# Overview
Currently, the bkr_info.py file specifies that it will check for provisioning updates once every minute for 60 minutes, and if the server isn't provisioned in that amount of time, than the provision has failed.

The amount of time you wait for the timeout should be a parameter you can pass along in the topology file.

**Comment by seandst** [comment]
I've been looking into this for a little bit now. Passing the information from the topology to where it can be useful to the provisioning request monitoring is tricky, but I think I see a way to get it done reliably. The provisioning check step has a few other tunables possibly worth exposing in addition to just the timeout, such as the frequency of checks and number of retries. I'll see about exposing all of those if it ends up being about as easy as exposing only one of them.

On the implementation side, support for an absolute "timeout" value needs to be added either way, since the current mechanism works with frequency and retry count alone.

**Comment by seandst** [comment]
@herlo where should I target development for this, and other beaker changes? Should it go here on develop, over in https://github.com/CentOS-PaaS-SIG/linchpin-providers-external, or somewhere else?

**Comment by herlo** [comment]
@seandst It would seem that the best place for now is in the develop branch. Please make sure the schema_v4 supports the change. It should be optional, and the default should be set in the playbook. Does this seem reasonable?

The linchpin-providers-external repository needs to be removed, as it's no longer in use and was only supporting v1.5+ anyway. I'll get it removed so it doesn't cause confusion in the future.

**Comment by seandst** [comment]
That's my plan.

In detail, the plan is roughly to...

- add support for a maximum timeout value that is effectively null by default, indicating the existing frequency/retry count mechanism should be used
- allow changing the retry count and retry frequency
- allow the maximum number of retries to be null if a timeout is set, so users can specify that checks should be retried until the timeout is reached rather than retrying a specific number of times
- document all of this in a way that doesn't make things confusing for beaker users
- ensure changes have no effect on existing beaker workflows that I use until/unless those workflows are modified to use the new customization values
