### ISSUE TITLE
Add ability to provision additional disks using the libvirt provisioner

### ISSUE THREAD

**Issue by dyasny** [CentOS-PaaS-SIG/linchpin#500]
We have a use case where we need to run a test with a VM that has additional volumes (e.g. a demo ceph cluster).
We would like to be able to specify this need in the libvirt topology.

parameters to define:

disk size
disk type (default to virtio_blk but being able to create virtio_scsi can be useful for shared disks that use SCSIv3)
shareable (default to false)

**Comment by herlo** [comment]
@dyasny at one time, I had libvirt_storage available, but never was able to get it included. Here's a topology example for the resource_definitions specifically.

https://github.com/CentOS-PaaS-SIG/linchpin/blob/release1.0/linchpin/examples/topologies/libvirt_storage.yml

Here's the xml I had templated at the time.

https://github.com/CentOS-PaaS-SIG/linchpin/blob/release1.0/linchpin/examples/libvirt/libvirt_storage.xml

LinchPin even had a schema for it (it's older and not in the cerberus schema format)

https://github.com/CentOS-PaaS-SIG/linchpin/blob/release1.0/linchpin/defaults/schemas/schema_v4.json#L624

I thought I had some playbooks lying around. I'll see if I can find them and provide them as well.

**Comment by 14rcole** [comment]
@dyasny in order to provision storage volumes, we first need to be able to provision storage pools.  Libvirt has the ability to provision both transient and persistent storage pools.  As of right now we've discussed allowing the transient pools to be associated with only one domain and automatically being destroyed when the domain is destroyed, and making no assumptions about which domains are using a particular persistent pool.  Therefore, the pool would have to be manually deleted.

For your use case, do you need one of the functions I described above, or do you not care?  Is there any changes you'd like us to make? Again, this is just regarding the pools in which the volumes would reside.

**Comment by dyasny** [comment]
@14rcole it is simple enough to leave storage pools alone and stick to simply generating a disk XML and attaching it, that's what I did to work around this issue. In short, for me at least, it would have been enough to be able to specify disks with size and type (virtio_blk/virtio_scsi/etc) and have them created and attached at the default storage pool, using the default local location. Really, over engineering is bad :)

Aaand, since I've left RH and don't work for the team that needed this fix, I'd suggest you reach out to @lukas-bednar and his colleagues

**Comment by herlo** [comment]
Fixed by #639
