### ISSUE TITLE
add option to toggle auto_ip for openstack deployments

### ISSUE THREAD

**Issue by dyasny** [CentOS-PaaS-SIG/linchpin#522]
Provisioning on Openstack will by default assign a floating IP even when fip isn't set in topology. To avoid that auto_ip: false needs to also be send to the os_server module. 

Please provide a way to set auto_ip so that it will be possible to provision instances without a floating IP assigned

**Comment by herlo** [comment]
@dyasny while looking into this issue today, I remembered why this was a bit of a challenge. The ansible role makes floating_ip_pools (fip_pool in the topology) and auto_ip mutually exclusive settings. It doesn't matter what value the 'auto_ip' values is set to, but rather if it's set at all. To that end, what I'm planning to do is create some basic logic to make them mutually exclusive in the topology schema, and the playbooks as well. 

My question is do you want to use the setting 'floating_ip_pools' with 'auto_ip: false'? How would you use these two settings in your use case? 

NOTE: It is possible to modify the os_server2 code to accommodate things, however, we're trying to get that code maintained by ansible again, rather than in linchpin. If we can help it, modifying the module will be a last resort.

**Comment by dyasny** [comment]
Basically, all I want is a way not to attach floating IPs to provisioned VMs. However the topology yaml syntax turns out to be is really irrelevant, I'll just follow the docs, and add the options you create for this

**Comment by herlo** [comment]
@dyasny Ok, that makes it simpler. I'll make sure to document that you cannot use these two settings together (and any others I find along the way), thanks!
