### ISSUE TITLE
RFE: Resource status during provisioning

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#869]
When multiple resources, or when provisioning takes a long time, it would be helpful to know in what state the provisioning is. For example, status like:
 - waiting for resource to be allocated
 - creating resource
 - system booting
 - waiting for ssh
 - running hook X

**Comment by samvarankashyap** [comment]
`Linchpin status` command line option which queries rundb periodically might be helpful for this issue.

**Comment by 14rcole** [comment]
The information that we can determine about a resource is largely based on what the target is willing to provide us with during provisioning.  I've started with beaker here since that seems to be the host for which this is most necessary.

In terms of the `bkr` cli, the best option is most likely to have a loop that runs `bkr job-results <job-id>`, and parses the xml to determine if the job is waiting, installing, or running. The loop would print the result to the screen and wait before repeating.  Then we can trigger a breakpoint when the job is running.

The other option is to run `bkr job-watch <job-id>` and figure out how to kill the command once the job is running.  That way we don't have to worry about output.

Neither option gives very granular information, but it's better than wondering if everything is going okay 45 minutes into a job

**Comment by samvarankashyap** [comment]
@abraverm Will be creating tickets for other providers.
