### ISSUE TITLE
Openstack volume with count fail with environment variables authentication

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#878]
The openstack example `docs/source/examples/workspaces/openstack` executed with environment variables authentication (OS_PASSWORD,...) fails:
```
TASK [openstack : provision/deprovision cinder volumes when count specified] ***
task path: /home/abraverm/.nextcloud/Work/cci-linchpin-docs/.venv/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_volume.yml:23
failed: [localhost] (item=[u'', u'volume', u'2', u'present', 0]) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth": "",
            "display_name": "volume_0",
            "interface": "public",
            "size": "2",
            "state": "present",
            "timeout": 180,
            "wait": true
        }
    },
    "msg": "argument auth is of type <type 'str'> and we were unable to convert to dict: dictionary requested, could not parse JSON or key=value",
    "vol": [
        "",
        "volume",
        "2",
        "present",
        0
    ]
}
```
The auth should be tested like `auth_var != ""`.  There is a lot of duplicate code in `provision_os_volume.yml` playbook that workarounds some issue of passing valid arguments to modules with three main cases: auth, count and async. I believe it could be minimized with set_fact, blocks and maybe [new loop][https://docs.ansible.com/ansible/2.7/user_guide/playbooks_loops.html#id13].

**Comment by samvarankashyap** [comment]
@abraverm The agree to issue with duplicate code. Moreover, due to limitations of the loop and condtional statements in  Ansible the above code duplication is one of the easiest way to implement  linchpin in accordance with older versions of Ansible. With respect to recent enhancements in Ansible I totally agree we need to revisit the playbook implementations to avoid duplication.
I am currently tagging the this issue as a bug and try to fix it in upcoming releases.
